version: '3.8'

services:

  backend:
    build: backend
    command: uvicorn backend.main:app --reload --workers 4 --host 0.0.0.0 --port 8001 --forwarded-allow-ips "*" --proxy-headers
    restart: unless-stopped
    volumes:
      - ./backend:/app/backend
    ports:
      - "8004:8001"
    environment:
      - DATABASE_URL=postgresql+asyncpg://notreal
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: notreal@notreal.com
      PGADMIN_DEFAULT_PASSWORD: notreal
    ports:
      - "5050:80"

  frontend:
    build: frontend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    tty: true

  
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  

volumes:
  postgres_data:

